containers/libkrunfw

patches/0004-x86-entry-build-thunk_-BITS-only-if-CONFIG_PREEMPTION-y.patch
Import patch https://lore.kernel.org/patchwork/patch/1369985/ for
fixing the build with newer binutils (was failing with 2.36-1.1.x86_64
on openSUSE Tumbleweed).
Addresses Issue #4.
Signed-off-by: Dario Faggioli <dfaggioli@suse.com>
=> patches/0004 x86/entry: build thunk_$(BITS) only if CONFIG_PREEMPTION=y

Makefile
Implement versioning for the output library by writing soname and
creating the corresponding symbolic links.
=> Makefile: add versioning to the output library

Makefile, patches-sev/0012-virtio-enable-DMA-API-if-memory-is-restricted.patch, patches-sev/0013-Allow-booting-SEV-ES-APs-without-GHCB-HACK.patch, patches/0001-krunfw-Don-t-panic-when-init-dies.patch, patches/0002-krunfw-Ignore-run_cmd-on-orderly-reboot.patch, patches/0003-virtio-vsock-add-VIRTIO_VSOCK_F_DGRAM-feature-bit.patch, patches/0004-virtio-vsock-add-support-for-virtio-datagram.patch, patches/0005-vhost-vsock-add-support-for-vhost-dgram.patch, patches/0006-vsock_test-add-tests-for-vsock-dgram.patch, patches/0007-virtio-vsock-add-sysfs-for-rx-buf-len-for-dgram.patch, patches/0008-virtio-vsock-Fix-DGRAM-polling.patch, patches/0009-virtio-vsock-add-DGRAM-to-virtio_transport_get_type.patch, patches/0010-Transparent-Socket-Impersonation-implementation.patch, patches/0011-tsi-allow-hijacking-sockets-tsi_hijack.patch
Update to the latest available LTS, 5.15.45. The patches still apply
cleanly, no need to update them.
=> Update to the latest LTS: 5.15.45

Makefile, patches-sev/0012-virtio-enable-DMA-API-if-memory-is-restricted.patch, patches-sev/0013-Allow-booting-SEV-ES-APs-without-GHCB-HACK.patch, patches/0001-krunfw-Don-t-panic-when-init-dies.patch, patches/0002-krunfw-Ignore-run_cmd-on-orderly-reboot.patch, patches/0003-virtio-vsock-add-VIRTIO_VSOCK_F_DGRAM-feature-bit.patch, patches/0004-virtio-vsock-add-support-for-virtio-datagram.patch, patches/0005-vhost-vsock-add-support-for-vhost-dgram.patch, patches/0006-vsock_test-add-tests-for-vsock-dgram.patch, patches/0007-virtio-vsock-add-sysfs-for-rx-buf-len-for-dgram.patch, patches/0008-virtio-vsock-Fix-DGRAM-polling.patch, patches/0009-virtio-vsock-add-DGRAM-to-virtio_transport_get_type.patch, patches/0010-Transparent-Socket-Impersonation-implementation.patch, patches/0011-tsi-allow-hijacking-sockets-tsi_hijack.patch
Rebase the kernel on the latest LTS (5.15.52). This is a clean rebase,
no changes needed in the patches.
=> Rebase kernel on v5.15.52

Makefile, patches-sev/0012-virtio-enable-DMA-API-if-memory-is-restricted.patch, patches-sev/0013-Allow-booting-SEV-ES-APs-without-GHCB-HACK.patch, patches/0001-krunfw-Don-t-panic-when-init-dies.patch, patches/0002-krunfw-Ignore-run_cmd-on-orderly-reboot.patch, patches/0003-virtio-vsock-add-VIRTIO_VSOCK_F_DGRAM-feature-bit.patch, patches/0004-virtio-vsock-add-support-for-virtio-datagram.patch, patches/0005-vhost-vsock-add-support-for-vhost-dgram.patch, patches/0006-vsock_test-add-tests-for-vsock-dgram.patch, patches/0007-virtio-vsock-add-sysfs-for-rx-buf-len-for-dgram.patch, patches/0008-virtio-vsock-Fix-DGRAM-polling.patch, patches/0009-virtio-vsock-add-DGRAM-to-virtio_transport_get_type.patch, patches/0010-Transparent-Socket-Impersonation-implementation.patch, patches/0011-tsi-allow-hijacking-sockets-tsi_hijack.patch
Rebase the kernel on the latest LTS (5.15.57). This is a clean rebase,
no changes needed in the patches.
=> Rebase kernel on v5.15.57

Makefile, patches-sev/0012-virtio-enable-DMA-API-if-memory-is-restricted.patch, patches-sev/0013-Allow-booting-SEV-ES-APs-without-GHCB-HACK.patch, patches/0001-krunfw-Don-t-panic-when-init-dies.patch, patches/0002-krunfw-Ignore-run_cmd-on-orderly-reboot.patch, patches/0003-virtio-vsock-add-VIRTIO_VSOCK_F_DGRAM-feature-bit.patch, patches/0004-virtio-vsock-add-support-for-virtio-datagram.patch, patches/0005-vhost-vsock-add-support-for-vhost-dgram.patch, patches/0006-vsock_test-add-tests-for-vsock-dgram.patch, patches/0007-virtio-vsock-add-sysfs-for-rx-buf-len-for-dgram.patch, patches/0008-virtio-vsock-Fix-DGRAM-polling.patch, patches/0009-virtio-vsock-add-DGRAM-to-virtio_transport_get_type.patch, patches/0010-Transparent-Socket-Impersonation-implementation.patch, patches/0011-tsi-allow-hijacking-sockets-tsi_hijack.patch
Rebase the kernel on the latest LTS (5.15.59). This is a clean rebase,
no changes needed in the patches.
=> Rebase kernel on v5.15.59

utils/Makefile, utils/sev_launch_measurement.c
Add a small utility for generating SEV launch measurements from a
libkrunfw library.
=> sev: add a utility for generating SEV LMs

Makefile
Having the "install" target depend on the existence of the library
triggers the rebuild of the library if some file has changed. This is
usually a desirable behavior, but becomes a problem with you try to
build and install multiple library flavors at the same time.
=> Makefile: drop library dependency on install

Makefile, README.md, build_on_krunvm.sh
This fixes #31 by automatically switching to the appropriate build script.
=> Automatically shift to `build_on_krunvm.sh`

Makefile
If the SONAME is used, libkrun gets linked to the full library version (x.y.z), which is inconvenient because it means we can't update libkrunfw without also update libkrun, even when updating to a newer minor release which is completely compatible.
To avoid this, only generate libkrunfw with ABI_VERSION on macOS.
=> macos: Don't use SONAME on macOS

README.md
Add the "Known Limitations" section, initially pointing the use of the CONFIG_NR_CPUS=8 option in the kernel config.
Fixes: containers/crun#1057
=> README.md: Add "Known Limitations" section

Makefile, patches-sev/0012-virtio-enable-DMA-API-if-memory-is-restricted.patch, patches-sev/0013-x86-sev-write-AP-reset-vector.patch, patches-sev/0014-Implement-driver-to-retrieve-secrets-from-cmdline.patch, patches-sev/0015-x86-sev-Avoid-using-native_cpuid.patch, patches/0001-krunfw-Don-t-panic-when-init-dies.patch, patches/0002-krunfw-Ignore-run_cmd-on-orderly-reboot.patch, patches/0003-virtio-vsock-add-VIRTIO_VSOCK_F_DGRAM-feature-bit.patch, patches/0004-virtio-vsock-add-support-for-virtio-datagram.patch, patches/0005-vhost-vsock-add-support-for-vhost-dgram.patch, patches/0006-vsock_test-add-tests-for-vsock-dgram.patch, patches/0007-virtio-vsock-add-sysfs-for-rx-buf-len-for-dgram.patch, patches/0008-virtio-vsock-Fix-DGRAM-polling.patch, patches/0009-virtio-vsock-add-DGRAM-to-virtio_transport_get_type.patch, patches/0010-Transparent-Socket-Impersonation-implementation.patch, patches/0011-tsi-allow-hijacking-sockets-tsi_hijack.patch
Rebase on the latest stable kernel (6.2.1). No big changes were required on the downstream patches.
Bump minor version to reflect the newer kernel, now at 3.10.0.
=> Rebase kernel on v6.2.1

Makefile, patches-sev/0012-virtio-enable-DMA-API-if-memory-is-restricted.patch, patches-sev/0013-x86-sev-write-AP-reset-vector.patch, patches-sev/0014-Implement-driver-to-retrieve-secrets-from-cmdline.patch, patches-sev/0015-x86-sev-Avoid-using-native_cpuid.patch, patches/0001-krunfw-Don-t-panic-when-init-dies.patch, patches/0002-krunfw-Ignore-run_cmd-on-orderly-reboot.patch, patches/0003-virtio-vsock-add-VIRTIO_VSOCK_F_DGRAM-feature-bit.patch, patches/0004-virtio-vsock-add-support-for-virtio-datagram.patch, patches/0005-vhost-vsock-add-support-for-vhost-dgram.patch, patches/0006-vsock_test-add-tests-for-vsock-dgram.patch, patches/0007-virtio-vsock-add-sysfs-for-rx-buf-len-for-dgram.patch, patches/0008-virtio-vsock-Fix-DGRAM-polling.patch, patches/0009-virtio-vsock-add-DGRAM-to-virtio_transport_get_type.patch, patches/0010-Transparent-Socket-Impersonation-implementation.patch, patches/0011-tsi-allow-hijacking-sockets-tsi_hijack.patch
Relatively small jump from 6.2.1 to 6.2.9. No significant changes required on the downstream patches.
Bump minor version to reflect the newer kernel, now at 3.11.0.
Update also initrd to pick up SNP support.
=> Rebase kernel on v6.2.9 and update initrd

bin2cbundle.py
In addition to padding the size of the bundle to 16K, tell GCC to align its beginning to that value.
This should fix loading the bundle in Apple Silicon without causing any trouble to other environments.
Fixes: containers/libkrun#132
=> Force bundle alignment to 16K

bin2cbundle.py
In addition to padding the size of the bundle to 64k, tell GCC to align its beginning to that value.
This should fix loading the bundle in 4k/16k/64k environments without causing any trouble smaller page size environments.
=> Force bundle alignment to 64K

build_on_krunvm.sh
Running `./build_on_krunvm.sh`, the kernel build works fine, but fails near the end with
```
OBJCOPY arch/arm64/boot/Image
GZIP    arch/arm64/boot/Image.gz
make[1]: Leaving directory '/work/linux-6.1.32'
Generating kernel.c from linux-6.1.32/arch/arm64/boot/Image...
Traceback (most recent call last):
File "/work/bin2cbundle.py", line 4, in <module>
from elftools.elf.elffile import ELFFile
ModuleNotFoundError: No module named 'elftools'
```
There is a missing package `python3-pyelftools`.
Also replaced the explicit list of packages to install with an installation of `dnf builddep` and using the depedencies for the kernel package.
Fixes #52
=> Add missing elftools to build-on-krunvm.sh

config-libkrunfw-sev_x86_64, config-libkrunfw_aarch64, config-libkrunfw_x86_64, patches/0010-Transparent-Socket-Impersonation-implementation.patch
This reverts commit ce7277c0504b6f2f0c369b2adb11e86f18ab6e57.
SELinux was enabled for crun-vm's [1] use case of running bootc-install, but the dependency on SELinux was since dropped.
Re-disable SELinux to avoid bloat. This has no effect on the x86_64 image since its defconfig includes CONFIG_SECURITY_SELINUX=y, but it should help reduce the aarch64 image size.
[1] https://github.com/containers/crun-vm
=> Revert "config: Enable CONFIG_SECURITY_SELINUX"

config-libkrunfw-sev_x86_64, config-libkrunfw_aarch64, config-libkrunfw_x86_64, patches/0010-Transparent-Socket-Impersonation-implementation.patch
As discussed offline, many workloads assume SELinux support. (Re)enable SELinux support.
=> config: Enable CONFIG_SECURITY_SELINUX

Makefile, patches-sev/0012-virtio-enable-DMA-API-if-memory-is-restricted.patch, patches-sev/0013-x86-sev-write-AP-reset-vector.patch, patches-sev/0014-Implement-driver-to-retrieve-secrets-from-cmdline.patch, patches-sev/0015-x86-sev-Avoid-using-native_cpuid.patch, patches/0001-krunfw-Don-t-panic-when-init-dies.patch, patches/0002-krunfw-Ignore-run_cmd-on-orderly-reboot.patch, patches/0003-vsock-dgram-generalize-recvmsg-and-drop-transport-dg.patch, patches/0004-vsock-refactor-transport-lookup-code.patch, patches/0005-vsock-support-multi-transport-datagrams.patch, patches/0006-vsock-make-vsock-bind-reusable.patch, patches/0007-virtio-vsock-add-VIRTIO_VSOCK_F_DGRAM-feature-bit.patch, patches/0008-virtio-vsock-support-dgrams.patch, patches/0009-tests-add-vsock-dgram-tests.patch, patches/0010-Transparent-Socket-Impersonation-implementation.patch, patches/0011-tsi-allow-hijacking-sockets-tsi_hijack.patch
Rebase on the latest LTS. No changes needed in the patches.
=> Rebase on a 6.6.44 kernel

utils/krunfw_measurement.c
...we need to use dlerror() instead.
=> utils/krunfw_measurement: dlopen() and dlsym() don't set errno

config-libkrunfw-sev_x86_64
We don't need ACPI and it breaks SNP, since it attempts to find the ACPI tables in unaccepted pages.
=> sev: add "acpi=off" to the bundled command line

.github/workflows/build-tdx.yml
Updates the init binary bundle to include a binary that does not do attestation when using the libkrun flavor. Built based on the work in this PR: https://github.com/containers/libkrun/pull/355 
Additionally adds a CI workflow to build the TDX kernel.
=> Update init binary and add TDX kernel build to CI
